version: '3.7'
services:
    # elastic01:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    #     container_name: elastic01
    #     environment:
    #         - discovery.type=single-node
    #         - bootstrap.memory_lock=true
    #         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1
    #     volumes:
    #         - elastic01:/usr/share/elasticsearch/data
    #     ports:
    #         - 9200:9200
    #     networks:
    #         - elastic
    # kibana01:
    #     image: docker.elastic.co/kibana/kibana:7.15.0
    #     container_name: kibana01
    #     ports:
    #         - 5601:5601
    #     environment:
    #         ELASTICSEARCH_URL: http://elastic01:9200
    #         ELASTICSEARCH_HOSTS: '["http://elastic01:9200"]'
    #     networks:
    #         - elastic
    database:
        image: 'mariadb:10.6.4'
        volumes:
            - ${PWD}/docker-volumes/mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: appvento
        ports:
            - '3319:3306'

volumes:
    mariadb-data:
        #elastic01:

        #networks:
        #    elastic:
        #        driver: bridge
